version: '3.7'
services:
  backend:
    build: 
        context: .
        target: ${GO_CONTAINER_BUILD_TARGET}
    tty: true
    volumes:
    - .:/usr/local/go/src/one-accounts
    env_file: .env
    depends_on:
      - mysql
    ports:
      - 8080:8080
    stdin_open: true
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/mysql_data:/var/lib/mysql
    env_file: .env.dev.db